//! Ordinal → name resolution for the OpenGL ES client DLLs.
//!
//! Games link OpenGL ES through the Khronos-defined import library,
//! which — like the Windows Mobile SDK's `coredll.lib` — strips export
//! names and imports purely by ordinal. Call of Duty 2's
//! `cod2_gles.exe` imports all 40 of its GL entry points from
//! `libGLES_CL.dll` as bare ordinals, so without a table there is no
//! way to tell `glDrawElements` from `glTexImage2D`.
//!
//! The tables in `data/` are generated by
//! `tools/generate-gles-ordinals.py` from the Khronos entry-point lists:
//! EGL first, then GL ES, each sorted by name, ordinal base 1. Only
//! names and their ordering are encoded — no vendor binary is copied.
//! The tests below pin the layout against the ordinals a real shipping
//! game imports.

use std::collections::HashMap;

use once_cell::sync::Lazy;
use serde::Deserialize;

const LIBGLES_CM_JSON: &str = include_str!("../data/libgles_cm-ordinals.json");
const LIBGLES_CL_JSON: &str = include_str!("../data/libgles_cl-ordinals.json");

/// Every DLL name that resolves to the Common profile table.
pub const CM_DLL_NAMES: [&str; 2] = ["libgles_cm.dll", "libgles_cm"];
/// Every DLL name that resolves to the Common-Lite profile table.
pub const CL_DLL_NAMES: [&str; 2] = ["libgles_cl.dll", "libgles_cl"];

#[derive(Debug, Deserialize)]
struct OrdinalFile {
    #[allow(dead_code)]
    dll: String,
    #[serde(rename = "ordinals")]
    map: HashMap<String, String>,
}

fn parse(dll: &str, json: &str) -> HashMap<u16, String> {
    match serde_json::from_str::<OrdinalFile>(json) {
        Ok(file) => file
            .map
            .into_iter()
            .filter_map(|(k, v)| k.parse::<u16>().ok().map(|ord| (ord, v)))
            .collect(),
        Err(e) => {
            log::error!("failed to parse GLES ordinal table for {dll}: {e}");
            HashMap::new()
        }
    }
}

static CM_TABLE: Lazy<HashMap<u16, String>> =
    Lazy::new(|| parse("libGLES_CM.dll", LIBGLES_CM_JSON));
static CL_TABLE: Lazy<HashMap<u16, String>> =
    Lazy::new(|| parse("libGLES_CL.dll", LIBGLES_CL_JSON));

/// Is `dll` one of the OpenGL ES client libraries we emulate?
pub fn is_gles_dll(dll: &str) -> bool {
    let key = dll.to_ascii_lowercase();
    CM_DLL_NAMES.contains(&key.as_str()) || CL_DLL_NAMES.contains(&key.as_str())
}

/// Look up the entry-point name for `ordinal` in `dll`.
pub fn lookup(dll: &str, ordinal: u16) -> Option<String> {
    let key = dll.to_ascii_lowercase();
    let table = if CM_DLL_NAMES.contains(&key.as_str()) {
        &*CM_TABLE
    } else if CL_DLL_NAMES.contains(&key.as_str()) {
        &*CL_TABLE
    } else {
        return None;
    };
    table.get(&ordinal).cloned()
}

/// Every entry-point name exported by `dll`, for `GetProcAddress`-style
/// dynamic resolution.
pub fn names_for(dll: &str) -> Vec<String> {
    let key = dll.to_ascii_lowercase();
    let table = if CM_DLL_NAMES.contains(&key.as_str()) {
        &*CM_TABLE
    } else if CL_DLL_NAMES.contains(&key.as_str()) {
        &*CL_TABLE
    } else {
        return Vec::new();
    };
    let mut names: Vec<String> = table.values().cloned().collect();
    names.sort();
    names.dedup();
    names
}

/// Number of ordinals known for `dll`.
pub fn entry_count(dll: &str) -> usize {
    let key = dll.to_ascii_lowercase();
    if CM_DLL_NAMES.contains(&key.as_str()) {
        CM_TABLE.len()
    } else if CL_DLL_NAMES.contains(&key.as_str()) {
        CL_TABLE.len()
    } else {
        0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_have_the_shipping_export_counts() {
        // A real libGLES_CM.dll from a Windows Mobile game exports 140
        // entry points (EGL 1.0/1.1/1.2 + GL ES 1.1 Common); the
        // Common-Lite profile drops the 29 float-only GL entry points
        // and the 9 EGL 1.1/1.2 additions, leaving 102.
        assert_eq!(entry_count("libgles_cm.dll"), 140);
        assert_eq!(entry_count("libgles_cl.dll"), 102);
    }

    #[test]
    fn cm_ordinals_match_a_shipping_dll_export_table() {
        // Spot-checked against the export directory of the
        // libGLES_CM.dll shipped in Call of Duty 2's installer CAB.
        // The EGL block occupies 1..=34 and GL starts at 35.
        for (ordinal, name) in [
            (1u16, "eglBindAPI"),
            (9, "eglCreateWindowSurface"),
            (17, "eglGetDisplay"),
            (21, "eglMakeCurrent"),
            (29, "eglSwapBuffers"),
            (34, "eglWaitNative"),
            (35, "glActiveTexture"),
            (40, "glClear"),
            (99, "glMatrixMode"),
            (133, "glTexImage2D"),
            (140, "glViewport"),
        ] {
            assert_eq!(
                lookup("libgles_cm.dll", ordinal).as_deref(),
                Some(name),
                "CM ordinal {ordinal}"
            );
        }
    }

    #[test]
    fn cl_ordinals_match_the_ordinals_cod2_imports() {
        // Ground truth: `cod2_gles.exe` imports libGLES_CL.dll purely
        // by ordinal, while its sibling `cod2_goforce.exe` imports the
        // *same* 40 entry points from libGLES_CM.dll by name and in the
        // same IAT order. Aligning the two directories positionally
        // gives an ordinal → name mapping straight out of a shipping
        // binary. These are the ones that pin the layout.
        for (ordinal, name) in [
            (1u16, "eglChooseConfig"),
            (3, "eglCreateContext"),
            (6, "eglCreateWindowSurface"),
            (8, "eglDestroySurface"),
            (10, "eglGetConfigs"),
            (14, "eglGetDisplay"),
            (17, "eglInitialize"),
            (18, "eglMakeCurrent"),
            (22, "eglSwapBuffers"),
            (23, "eglTerminate"),
            (26, "glActiveTexture"),
            (28, "glBindTexture"),
            (30, "glClear"),
            (31, "glClearColorx"),
            (34, "glClientActiveTexture"),
            (43, "glDeleteTextures"),
            (50, "glDrawElements"),
            (58, "glFrustumx"),
            (63, "glHint"),
            (69, "glLoadIdentity"),
            (70, "glLoadMatrixx"),
            (74, "glMatrixMode"),
            (90, "glShadeModel"),
            (94, "glTexCoordPointer"),
            (97, "glTexImage2D"),
            (101, "glVertexPointer"),
            (102, "glViewport"),
        ] {
            assert_eq!(
                lookup("libgles_cl.dll", ordinal).as_deref(),
                Some(name),
                "CL ordinal {ordinal}"
            );
        }
    }

    #[test]
    fn common_lite_omits_the_float_entry_points() {
        // The whole point of the Common-Lite profile: no `*f` variants.
        // If these leaked in, every ordinal above them would shift and
        // the guest would call the wrong function entirely.
        let cl = names_for("libgles_cl.dll");
        assert!(!cl.iter().any(|n| n == "glFogf"));
        assert!(!cl.iter().any(|n| n == "glFrustumf"));
        assert!(!cl.iter().any(|n| n == "glLoadMatrixf"));
        // But the fixed-point ones are present in both.
        assert!(cl.iter().any(|n| n == "glFogx"));
        let cm = names_for("libgles_cm.dll");
        assert!(cm.iter().any(|n| n == "glFogf"));
        assert!(cm.iter().any(|n| n == "glFogx"));
    }

    #[test]
    fn recognises_both_client_library_names() {
        assert!(is_gles_dll("libGLES_CM.dll"));
        assert!(is_gles_dll("libgles_cl.dll"));
        assert!(!is_gles_dll("coredll.dll"));
    }

    #[test]
    fn unknown_ordinals_resolve_to_none() {
        assert_eq!(lookup("libgles_cm.dll", 0), None);
        assert_eq!(lookup("libgles_cm.dll", 141), None);
        assert_eq!(lookup("libgles_cl.dll", 103), None);
    }
}
